spring:
  application:
    # 应用名称
    name: sp-foreground
  datasource:
    url: jdbc:mysql://localhost:3306/sp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

server:
  # 端口号
  port: 8088

mybatis:
  mapper-locations:
    - classpath*:cn/**/mapper/*.xml
    - classpath:dao/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: sp-foreground-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /user/login
      - /user/register
#application.name
dubbo:
  application:
    name: sp-foreground
  registry:
    address: zookeeper://127.0.0.1:2181

sp:
  service:
    version: 1.0.0