# 应用名称
spring:
  application:
    name: sp-service
  datasource:
    url: jdbc:mysql://localhost:3306/sp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
server:
  port: 8086
dubbo:
  application:
    name: sp-base-service
  scan:
    base-packages: cn.yuanyuan.sp.service.impl
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880

sp:
  service:
    version: 1.0.0

mybatis:
  mapper-locations:
    - classpath*:cn/**/mapper/*.xml
    - classpath:dao/*.xml